// Contenido real de las lecciones, organizado por el id del tema.
// Nivel 0 (temas 1-5): 50 preguntas por tema con variedad de tipos.
// Resto de temas: 5 preguntas por ahora (se irán ampliando por nivel).

export interface PreguntaLeccion {
  id: number;
  ingles: string;
  espanol: string;
  opciones: string[];
  correcta: number;
}

export const leccionesPorTema: Record<number, PreguntaLeccion[]> = {
  // ── NIVEL 0 ─────────────────────────────────────────────────────────────

  // Tema 1: Saludos y despedidas
  1: [

    { id: 1,  ingles: 'Hello! How are you?',                    espanol: '¡Hola! ¿Cómo estás?',                    opciones: ["I'm fine, thank you!", 'Goodbye!', 'My name is Diego.'],          correcta: 0 },
    { id: 2,  ingles: 'Good morning!',                          espanol: '¡Buenos días!',                           opciones: ['Good night!', 'Good morning!', 'See you soon!'],                   correcta: 1 },
    { id: 3,  ingles: 'Nice to meet you!',                      espanol: '¡Mucho gusto!',                           opciones: ['See you later!', 'Nice to meet you too!', 'I am tired.'],         correcta: 1 },
    { id: 4,  ingles: 'What do you say when you leave?',        espanol: '¿Qué dices cuando te vas?',               opciones: ['Goodbye, see you tomorrow!', 'How are you?', 'Nice to meet you!'],correcta: 0 },
    { id: 5,  ingles: 'How was your day?',                      espanol: '¿Cómo estuvo tu día?',                   opciones: ['It was great, thank you!', 'My name is Diego.', 'Good morning!'],  correcta: 0 },
    { id: 6,  ingles: '¿Cómo se dice "buenas tardes"?',        espanol: 'Traducción al inglés',                   opciones: ['Good afternoon!', 'Good morning!', 'Good night!'],                 correcta: 0 },
    { id: 7,  ingles: 'Someone says "Good night!" to you. You reply:',  espanol: 'Alguien te dice "¡Buenas noches!" Respondes:', opciones: ['Good night! Sleep well!', 'Good morning!', 'See you later!'], correcta: 0 },
    { id: 8,  ingles: '___ to meet you! I am Ana.',             espanol: 'Completa: ___ conocerte. Soy Ana.',       opciones: ['Nice', 'Good', 'Hello'],                                           correcta: 0 },
    { id: 9,  ingles: 'How do you greet someone in the morning?', espanol: '¿Cómo saludas a alguien en la mañana?', opciones: ['Good morning!', 'Good night!', 'Goodbye!'],                       correcta: 0 },
    { id: 10, ingles: '¿Cómo se dice "hasta luego"?',           espanol: 'Traducción al inglés',                   opciones: ['See you later!', 'Good morning!', 'Nice to meet you!'],           correcta: 0 },
    { id: 11, ingles: 'You meet your friend after a long time. You say:', espanol: 'Ves a tu amigo después de mucho tiempo. Dices:', opciones: ['Long time no see!', 'Good night!', 'Excuse me.'],  correcta: 0 },
    { id: 12, ingles: 'I am ___ to see you again!',             espanol: 'Estoy ___ de verte de nuevo.',           opciones: ['happy', 'sad', 'tired'],                                          correcta: 0 },
    { id: 13, ingles: '¿Cómo se dice "¿Cómo te llamas?"?',     espanol: 'Traducción al inglés',                   opciones: ['What is your name?', 'How are you?', 'Where are you from?'],      correcta: 0 },
    { id: 14, ingles: 'Someone asks "How are you?" You answer:', espanol: 'Alguien pregunta "¿Cómo estás?" Respondes:', opciones: ["I'm doing well, thanks!", "I'm a student.", 'Good morning!'], correcta: 0 },
    { id: 15, ingles: 'What do you say when you first meet someone?', espanol: '¿Qué dices cuando conoces a alguien por primera vez?', opciones: ['Nice to meet you!', 'Goodbye!', 'Good night!'], correcta: 0 },
    { id: 16, ingles: '___ morning! Did you sleep well?',        espanol: '___ mañana! ¿Dormiste bien?',            opciones: ['Good', 'Nice', 'Fine'],                                           correcta: 0 },
    { id: 17, ingles: '¿Cómo se dice "con mucho gusto"?',       espanol: 'Traducción al inglés',                   opciones: ['My pleasure!', 'No problem!', 'Of course!'],                      correcta: 0 },
    { id: 18, ingles: 'Your teacher greets you. You reply:',    espanol: 'Tu profesor te saluda. Respondes:',      opciones: ['Good morning, teacher!', 'Goodbye!', 'See you later!'],            correcta: 0 },
    { id: 19, ingles: 'See you ___! (hasta mañana)',            espanol: 'Completa la despedida.',                 opciones: ['tomorrow', 'yesterday', 'now'],                                    correcta: 0 },
    { id: 20, ingles: '¿Cómo se dice "¿Cómo estás?"?',         espanol: 'Traducción al inglés',                   opciones: ['How are you?', 'What is your name?', 'Where do you live?'],       correcta: 0 },
    { id: 21, ingles: 'You pass someone in the hall. You say:', espanol: 'Pasas a alguien en el pasillo. Dices:',  opciones: ['Hi! How are you?', 'Goodbye forever!', 'Nice to meet you!'],      correcta: 0 },
    { id: 22, ingles: 'It is late at night. You say ___.',      espanol: 'Es tarde en la noche. Dices ___.',       opciones: ['Good night!', 'Good morning!', 'Good afternoon!'],                 correcta: 0 },
    { id: 23, ingles: '¿Cómo se dice "encantado de conocerte"?', espanol: 'Traducción al inglés',                 opciones: ['Pleased to meet you!', 'How are you?', 'See you later!'],          correcta: 0 },
    { id: 24, ingles: 'Someone says "Nice to meet you!" You reply:', espanol: 'Alguien dice "¡Mucho gusto!" Respondes:', opciones: ['Nice to meet you too!', 'Goodbye!', 'Good morning!'],       correcta: 0 },
    { id: 25, ingles: '___ afternoon! How was your lunch?',     espanol: '___ tarde! ¿Cómo estuvo tu almuerzo?',   opciones: ['Good', 'Nice', 'Well'],                                           correcta: 0 },
    { id: 26, ingles: '¿Cómo se dice "nos vemos pronto"?',      espanol: 'Traducción al inglés',                   opciones: ['See you soon!', 'Goodbye!', 'Nice to meet you!'],                 correcta: 0 },
    { id: 27, ingles: 'You are leaving a party. You say:',      espanol: 'Te vas de una fiesta. Dices:',           opciones: ['Thanks for having me! Goodbye!', 'Good morning!', 'Nice to meet you!'], correcta: 0 },
    { id: 28, ingles: 'Hello! My ___ is Carlos.',               espanol: 'Hola! Mi ___ es Carlos.',                opciones: ['name', 'age', 'color'],                                           correcta: 0 },
    { id: 29, ingles: '¿Cómo se dice "disculpe"?',              espanol: 'Traducción al inglés',                   opciones: ['Excuse me!', 'Thank you!', 'Goodbye!'],                           correcta: 0 },
    { id: 30, ingles: 'It is 3 in the afternoon. You greet someone:', espanol: 'Son las 3 de la tarde. Saludas a alguien:', opciones: ['Good afternoon!', 'Good morning!', 'Good night!'],       correcta: 0 },
    { id: 31, ingles: 'You answer the phone. You say:',         espanol: 'Contestas el teléfono. Dices:',          opciones: ['Hello! Who is this?', 'Goodbye!', 'Good night!'],                 correcta: 0 },
    { id: 32, ingles: '___ to see you! Come in!',               espanol: '___ verte. ¡Entra!',                     opciones: ['Great', 'Bad', 'Tired'],                                          correcta: 0 },
    { id: 33, ingles: '¿Cómo se dice "mucho gusto en conocerle"?', espanol: 'Traducción formal al inglés',        opciones: ['It is a pleasure to meet you.', 'How are you?', 'See you later!'], correcta: 0 },
    { id: 34, ingles: 'A stranger asks for your name. You say:', espanol: 'Un desconocido pregunta tu nombre. Dices:', opciones: ['My name is Diego. Nice to meet you!', 'Goodbye!', 'Good morning!'], correcta: 0 },
    { id: 35, ingles: 'Hi ___! Long time no see!',              espanol: '¡Hola ___! ¡Cuánto tiempo!',             opciones: ['there', 'here', 'now'],                                           correcta: 0 },
    { id: 36, ingles: '¿Cómo se dice "igualmente"?',            espanol: 'Traducción al inglés',                   opciones: ['Likewise!', 'Goodbye!', 'Good morning!'],                         correcta: 0 },
    { id: 37, ingles: 'Your friend is leaving. You say:',       espanol: 'Tu amigo se va. Dices:',                 opciones: ['Take care! Bye!', 'Good morning!', 'Nice to meet you!'],          correcta: 0 },
    { id: 38, ingles: 'How ___ you? I have not seen you in ages!', espanol: '¿Cómo ___? ¡No te veía hace mucho!', opciones: ['are', 'is', 'am'],                                                correcta: 0 },
    { id: 39, ingles: '¿Cómo se dice "hasta la próxima"?',      espanol: 'Traducción al inglés',                   opciones: ['Until next time!', 'Good morning!', 'Nice to meet you!'],         correcta: 0 },
    { id: 40, ingles: 'You run into your neighbor. You say:',   espanol: 'Te encuentras con tu vecino. Dices:',    opciones: ['Hi! How are things?', 'Goodbye forever!', 'Good night!'],         correcta: 0 },
    { id: 41, ingles: 'Good ___, everyone! Let us start class.', espanol: 'Buenos ___, ¡empecemos la clase!',      opciones: ['morning', 'night', 'bye'],                                        correcta: 0 },
    { id: 42, ingles: '¿Cómo se dice "qué tal"?',               espanol: 'Traducción informal al inglés',          opciones: ['What is up?', 'Good night!', 'Goodbye!'],                         correcta: 0 },
    { id: 43, ingles: 'Someone says "What is up?" You reply:',  espanol: 'Alguien dice "¿Qué tal?" Respondes:',   opciones: ['Not much, just chilling!', 'Good night!', 'Nice to meet you!'],   correcta: 0 },
    { id: 44, ingles: 'It was ___ meeting you today!',          espanol: 'Fue ___ conocerte hoy.',                 opciones: ['great', 'bad', 'boring'],                                         correcta: 0 },
    { id: 45, ingles: '¿Cómo se dice "que tengas un buen día"?', espanol: 'Traducción al inglés',                 opciones: ['Have a great day!', 'Good night!', 'See you tomorrow!'],          correcta: 0 },
    { id: 46, ingles: 'You are introduced to your boss. You say:', espanol: 'Te presentan a tu jefe. Dices:',      opciones: ['It is a pleasure to meet you, sir.', 'Hey! What is up?', 'Bye!'], correcta: 0 },
    { id: 47, ingles: 'Bye ___! Have a safe trip!',             espanol: '¡Adiós ___! ¡Buen viaje!',              opciones: ['for now', 'forever', 'always'],                                   correcta: 0 },
    { id: 48, ingles: '¿Cómo se dice "bienvenido"?',            espanol: 'Traducción al inglés',                   opciones: ['Welcome!', 'Goodbye!', 'Good morning!'],                          correcta: 0 },
    { id: 49, ingles: 'Someone welcomes you. You reply:',       espanol: 'Alguien te da la bienvenida. Respondes:', opciones: ['Thank you! Happy to be here!', 'Goodbye!', 'Good night!'],       correcta: 0 },
    { id: 50, ingles: 'I hope to ___ you again soon!',          espanol: 'Espero ___ verte pronto.',               opciones: ['see', 'meet', 'find'],                                            correcta: 0 },
  ],

  // Tema 2: Números y fechas
  2: [

    { id: 1,  ingles: 'How many apples do you have?',           espanol: '¿Cuántas manzanas tienes?',              opciones: ['I have three apples.', 'I have blue apples.', 'I have an apple today.'], correcta: 0 },
    { id: 2,  ingles: 'What day is it today?',                  espanol: '¿Qué día es hoy?',                       opciones: ["It is ten o'clock.", 'Today is Monday.', 'It is January.'],        correcta: 1 },
    { id: 3,  ingles: 'What is the number after nine?',         espanol: '¿Cuál es el número después del nueve?',  opciones: ['Eight', 'Eleven', 'Ten'],                                          correcta: 2 },
    { id: 4,  ingles: 'When is your birthday?',                 espanol: '¿Cuándo es tu cumpleaños?',              opciones: ['My birthday is in May.', 'I am five years old.', 'It is Tuesday.'],correcta: 0 },
    { id: 5,  ingles: 'How old are you?',                       espanol: '¿Cuántos años tienes?',                  opciones: ['I am fine.', 'I am 25 years old.', 'I like music.'],               correcta: 1 },
    { id: 6,  ingles: '¿Cómo se dice "quince"?',               espanol: 'Traducción al inglés',                   opciones: ['Fifteen', 'Fifty', 'Five'],                                        correcta: 0 },
    { id: 7,  ingles: 'Today is the ___ of March. (3ro)',       espanol: 'Hoy es el ___ de marzo.',                opciones: ['third', 'tree', 'three'],                                          correcta: 0 },
    { id: 8,  ingles: 'Someone asks your age. You say:',        espanol: 'Alguien pregunta tu edad. Dices:',       opciones: ['I am twenty years old.', 'I am Monday.', 'I have five.'],         correcta: 0 },
    { id: 9,  ingles: 'What comes after twenty?',               espanol: '¿Qué viene después del veinte?',         opciones: ['Twenty-one', 'Nineteen', 'Twelve'],                                correcta: 0 },
    { id: 10, ingles: '¿Cómo se dice "cien"?',                 espanol: 'Traducción al inglés',                   opciones: ['One hundred', 'Ten', 'One thousand'],                              correcta: 0 },
    { id: 11, ingles: 'The meeting is on the ___ of July. (5to)', espanol: 'La reunión es el ___ de julio.',      opciones: ['fifth', 'five', 'fiver'],                                          correcta: 0 },
    { id: 12, ingles: 'How do you say 2024 in English?',        espanol: '¿Cómo se dice 2024 en inglés?',         opciones: ['Two thousand and twenty-four', 'Twenty twenty-four', 'Both are correct'], correcta: 2 },
    { id: 13, ingles: '¿Cómo se dice "primero"?',              espanol: 'Traducción ordinal al inglés',           opciones: ['First', 'One', 'Once'],                                            correcta: 0 },
    { id: 14, ingles: 'Someone says their birthday is March 15th. You ask:', espanol: 'Alguien dice que su cumple es el 15 de marzo. Preguntas:', opciones: ['What year were you born?', 'What color is March?', 'Do you like cake?'], correcta: 0 },
    { id: 15, ingles: 'There are ___ days in a week.',          espanol: 'Hay ___ días en una semana.',            opciones: ['seven', 'five', 'ten'],                                            correcta: 0 },
    { id: 16, ingles: '¿Cómo se dice "segundo"?',              espanol: 'Traducción ordinal al inglés',           opciones: ['Second', 'Two', 'Twice'],                                          correcta: 0 },
    { id: 17, ingles: 'What month comes after March?',          espanol: '¿Qué mes viene después de marzo?',       opciones: ['April', 'February', 'May'],                                        correcta: 0 },
    { id: 18, ingles: 'The store opens at ___ in the morning. (9)', espanol: 'La tienda abre a las ___ de la mañana.', opciones: ['nine', 'nineteen', 'ninety'],                               correcta: 0 },
    { id: 19, ingles: '¿Cómo se dice "mil"?',                  espanol: 'Traducción al inglés',                   opciones: ['One thousand', 'One hundred', 'One million'],                      correcta: 0 },
    { id: 20, ingles: 'Someone asks what day it is. You say:',  espanol: 'Alguien pregunta qué día es. Dices:',    opciones: ['Today is Wednesday.', 'Today is blue.', 'Today is five.'],         correcta: 0 },
    { id: 21, ingles: 'How many months are in a year?',         espanol: '¿Cuántos meses hay en un año?',          opciones: ['Twelve', 'Ten', 'Eight'],                                          correcta: 0 },
    { id: 22, ingles: '¿Cómo se dice "veinte"?',               espanol: 'Traducción al inglés',                   opciones: ['Twenty', 'Twelve', 'Two'],                                         correcta: 0 },
    { id: 23, ingles: 'My phone number is ___ (555). In English:', espanol: 'Mi número es ___. En inglés:',       opciones: ['five five five', 'five hundred fifty five', 'fifty-five five'],    correcta: 0 },
    { id: 24, ingles: 'The class starts at ___ thirty. (8)',    espanol: 'La clase empieza a las ___ treinta.',    opciones: ['eight', 'eighteen', 'eighty'],                                     correcta: 0 },
    { id: 25, ingles: '¿Cómo se dice "tercero"?',              espanol: 'Traducción ordinal al inglés',           opciones: ['Third', 'Three', 'Thirteen'],                                      correcta: 0 },
    { id: 26, ingles: 'Today is Monday. Tomorrow is ___.',      espanol: 'Hoy es lunes. Mañana es ___.',           opciones: ['Tuesday', 'Sunday', 'Wednesday'],                                  correcta: 0 },
    { id: 27, ingles: '¿Cómo se dice "cuarenta"?',             espanol: 'Traducción al inglés',                   opciones: ['Forty', 'Fourteen', 'Four'],                                       correcta: 0 },
    { id: 28, ingles: 'Someone asks "When is Christmas?" You say:', espanol: 'Alguien pregunta "¿Cuándo es Navidad?" Dices:', opciones: ['It is on December twenty-fifth.', 'It is on Monday.', 'It is in summer.'], correcta: 0 },
    { id: 29, ingles: 'There are ___ hours in a day.',          espanol: 'Hay ___ horas en un día.',               opciones: ['twenty-four', 'twelve', 'twenty'],                                 correcta: 0 },
    { id: 30, ingles: '¿Cómo se dice "cincuenta"?',            espanol: 'Traducción al inglés',                   opciones: ['Fifty', 'Fifteen', 'Five'],                                        correcta: 0 },
    { id: 31, ingles: 'What is the last month of the year?',   espanol: '¿Cuál es el último mes del año?',        opciones: ['December', 'January', 'November'],                                 correcta: 0 },
    { id: 32, ingles: 'I was born in ___. (1998)',              espanol: 'Nací en ___.',                           opciones: ['nineteen ninety-eight', 'one thousand nine hundred ninety-eight', 'nineteen eighty-nine'], correcta: 0 },
    { id: 33, ingles: '¿Cómo se dice "noveno"?',               espanol: 'Traducción ordinal al inglés',           opciones: ['Ninth', 'Nine', 'Nineteen'],                                       correcta: 0 },
    { id: 34, ingles: 'Someone texts you their number. You read it as:', espanol: 'Alguien te manda su número. Lo lees como:', opciones: ['Each digit separately', 'As one big number', 'In Spanish'], correcta: 0 },
    { id: 35, ingles: 'The year has ___ weeks.',                espanol: 'El año tiene ___ semanas.',              opciones: ['fifty-two', 'forty', 'sixty'],                                     correcta: 0 },
    { id: 36, ingles: '¿Cómo se dice "millón"?',               espanol: 'Traducción al inglés',                   opciones: ['One million', 'One thousand', 'One billion'],                      correcta: 0 },
    { id: 37, ingles: 'It is a quarter past ___. (3:15)',       espanol: 'Son las ___ y cuarto.',                  opciones: ['three', 'thirteen', 'thirty'],                                     correcta: 0 },
    { id: 38, ingles: 'How many seasons are there in a year?',  espanol: '¿Cuántas estaciones hay en un año?',    opciones: ['Four', 'Three', 'Two'],                                            correcta: 0 },
    { id: 39, ingles: '¿Cómo se dice "doce"?',                 espanol: 'Traducción al inglés',                   opciones: ['Twelve', 'Twenty', 'Two'],                                         correcta: 0 },
    { id: 40, ingles: 'Someone asks what time it is. It is 7:00. You say:', espanol: 'Preguntan la hora. Son las 7:00. Dices:', opciones: ["It's seven o'clock.", "It's seven hundred.", "It's the seventh hour."], correcta: 0 },
    { id: 41, ingles: 'My favorite number is ___. (13)',        espanol: 'Mi número favorito es ___.',             opciones: ['thirteen', 'thirty', 'three'],                                     correcta: 0 },
    { id: 42, ingles: '¿Cómo se dice "octavo"?',               espanol: 'Traducción ordinal al inglés',           opciones: ['Eighth', 'Eight', 'Eighty'],                                       correcta: 0 },
    { id: 43, ingles: 'Today is Friday. The day after tomorrow is ___.',  espanol: 'Hoy es viernes. Pasado mañana es ___.',  opciones: ['Sunday', 'Saturday', 'Monday'],                          correcta: 0 },
    { id: 44, ingles: 'How many zeros are in one million?',     espanol: '¿Cuántos ceros tiene un millón?',        opciones: ['Six', 'Five', 'Seven'],                                            correcta: 0 },
    { id: 45, ingles: '¿Cómo se dice "sexto"?',                espanol: 'Traducción ordinal al inglés',           opciones: ['Sixth', 'Six', 'Sixteen'],                                         correcta: 0 },
    { id: 46, ingles: 'Someone asks your birthday. You say:',   espanol: 'Alguien pregunta tu cumple. Dices:',     opciones: ['My birthday is on July fourth.', 'My birthday is blue.', 'I like birthdays.'], correcta: 0 },
    { id: 47, ingles: 'There are ___ minutes in an hour.',      espanol: 'Hay ___ minutos en una hora.',           opciones: ['sixty', 'fifty', 'seventy'],                                       correcta: 0 },
    { id: 48, ingles: '¿Cómo se dice "décimo"?',               espanol: 'Traducción ordinal al inglés',           opciones: ['Tenth', 'Ten', 'Tenth teen'],                                      correcta: 0 },
    { id: 49, ingles: 'The movie starts at half past ___. (6:30)', espanol: 'La película empieza a las ___ y media.', opciones: ['six', 'sixteen', 'sixty'],                                    correcta: 0 },
    { id: 50, ingles: 'Two plus three equals ___.',             espanol: 'Dos más tres es igual a ___.',           opciones: ['five', 'six', 'four'],                                             correcta: 0 },
  ],

  // Tema 3: Colores y formas
  3: [

    { id: 1,  ingles: 'What color is the sky?',                 espanol: '¿De qué color es el cielo?',             opciones: ['The sky is blue.', 'The sky is square.', 'The sky is fast.'],    correcta: 0 },
    { id: 2,  ingles: 'A stop sign has this shape:',            espanol: 'Una señal de alto tiene esta forma:',    opciones: ['Circle', 'Octagon', 'Triangle'],                                  correcta: 1 },
    { id: 3,  ingles: 'What color do you get mixing blue and yellow?', espanol: '¿Qué color sale de mezclar azul y amarillo?', opciones: ['Green', 'Purple', 'Orange'],                          correcta: 0 },
    { id: 4,  ingles: 'A ball is usually shaped like a ___.',   espanol: 'Una pelota tiene forma de ___.',         opciones: ['square', 'sphere', 'rectangle'],                                  correcta: 1 },
    { id: 5,  ingles: 'What color is grass?',                   espanol: '¿De qué color es el pasto?',             opciones: ['Green', 'Red', 'Black'],                                          correcta: 0 },
    { id: 6,  ingles: '¿Cómo se dice "morado"?',               espanol: 'Traducción al inglés',                   opciones: ['Purple', 'Orange', 'Brown'],                                      correcta: 0 },
    { id: 7,  ingles: 'Someone asks the color of your shirt. It is red. You say:', espanol: 'Preguntan el color de tu camisa. Es roja. Dices:', opciones: ['My shirt is red.', 'My shirt is circle.', 'My shirt is big.'], correcta: 0 },
    { id: 8,  ingles: 'A triangle has ___ sides.',              espanol: 'Un triángulo tiene ___ lados.',          opciones: ['three', 'four', 'two'],                                           correcta: 0 },
    { id: 9,  ingles: 'What color do you get mixing red and white?', espanol: '¿Qué color sale de mezclar rojo y blanco?', opciones: ['Pink', 'Purple', 'Orange'],                               correcta: 0 },
    { id: 10, ingles: '¿Cómo se dice "naranja"?',              espanol: 'Traducción al inglés',                   opciones: ['Orange', 'Yellow', 'Red'],                                        correcta: 0 },
    { id: 11, ingles: 'You want to describe a sunny day. You say:', espanol: 'Describes un día soleado. Dices:',   opciones: ['The sky is bright blue today!', 'The sky is square today!', 'The sky is Monday!'], correcta: 0 },
    { id: 12, ingles: 'A square has ___ equal sides.',          espanol: 'Un cuadrado tiene ___ lados iguales.',  opciones: ['four', 'three', 'six'],                                           correcta: 0 },
    { id: 13, ingles: '¿Cómo se dice "gris"?',                 espanol: 'Traducción al inglés',                   opciones: ['Gray', 'Brown', 'Black'],                                         correcta: 0 },
    { id: 14, ingles: 'The traffic light is ___. You must stop.', espanol: 'El semáforo está en ___. Debes parar.', opciones: ['red', 'green', 'blue'],                                         correcta: 0 },
    { id: 15, ingles: 'What shape is a pizza?',                 espanol: '¿Qué forma tiene una pizza?',            opciones: ['Circle', 'Square', 'Triangle'],                                   correcta: 0 },
    { id: 16, ingles: '¿Cómo se dice "marrón" o "café"?',      espanol: 'Traducción al inglés',                   opciones: ['Brown', 'Gray', 'Beige'],                                         correcta: 0 },
    { id: 17, ingles: 'Someone shows you a yellow flower. You say:', espanol: 'Alguien te muestra una flor amarilla. Dices:', opciones: ['What a beautiful yellow flower!', 'What a blue triangle!', 'What a big number!'], correcta: 0 },
    { id: 18, ingles: 'A rectangle has ___ sides.',             espanol: 'Un rectángulo tiene ___ lados.',         opciones: ['four', 'three', 'five'],                                          correcta: 0 },
    { id: 19, ingles: '¿Cómo se dice "rosado"?',               espanol: 'Traducción al inglés',                   opciones: ['Pink', 'Red', 'Purple'],                                          correcta: 0 },
    { id: 20, ingles: 'The traffic light is ___. You can go!',  espanol: 'El semáforo está en ___. ¡Puedes ir!',  opciones: ['green', 'red', 'yellow'],                                         correcta: 0 },
    { id: 21, ingles: 'What color is snow?',                    espanol: '¿De qué color es la nieve?',             opciones: ['White', 'Blue', 'Gray'],                                          correcta: 0 },
    { id: 22, ingles: '¿Cómo se dice "turquesa"?',             espanol: 'Traducción al inglés',                   opciones: ['Turquoise', 'Teal', 'Cyan'],                                      correcta: 0 },
    { id: 23, ingles: 'You are buying a car and want a dark color. You say:', espanol: 'Compras un carro y quieres un color oscuro. Dices:', opciones: ['I would like it in black or dark blue.', 'I want it in pink or yellow.', 'I need a circle car.'], correcta: 0 },
    { id: 24, ingles: 'A star shape usually has ___ points.',   espanol: 'Una estrella usualmente tiene ___ puntas.', opciones: ['five', 'four', 'six'],                                        correcta: 0 },
    { id: 25, ingles: '¿Cómo se dice "negro"?',                espanol: 'Traducción al inglés',                   opciones: ['Black', 'Dark', 'Gray'],                                          correcta: 0 },
    { id: 26, ingles: 'The leaves on the trees are ___.',       espanol: 'Las hojas de los árboles son ___.',      opciones: ['green', 'blue', 'red'],                                           correcta: 0 },
    { id: 27, ingles: 'What shape is a book?',                  espanol: '¿Qué forma tiene un libro?',             opciones: ['Rectangle', 'Circle', 'Triangle'],                                correcta: 0 },
    { id: 28, ingles: '¿Cómo se dice "dorado"?',               espanol: 'Traducción al inglés',                   opciones: ['Golden', 'Yellow', 'Orange'],                                     correcta: 0 },
    { id: 29, ingles: 'Someone asks about the color of the ocean. You say:', espanol: 'Preguntan el color del océano. Dices:', opciones: ['The ocean is deep blue.', 'The ocean is square.', 'The ocean is Monday.'], correcta: 0 },
    { id: 30, ingles: 'A diamond shape has ___ sides.',         espanol: 'Un rombo tiene ___ lados.',              opciones: ['four', 'three', 'five'],                                          correcta: 0 },
    { id: 31, ingles: '¿Cómo se dice "plateado"?',             espanol: 'Traducción al inglés',                   opciones: ['Silver', 'Gray', 'White'],                                        correcta: 0 },
    { id: 32, ingles: 'What color is a banana?',                espanol: '¿De qué color es un banano?',            opciones: ['Yellow', 'Orange', 'Green'],                                      correcta: 0 },
    { id: 33, ingles: 'A circle has ___ sides.',                espanol: 'Un círculo tiene ___ lados.',            opciones: ['no sides', 'four sides', 'two sides'],                            correcta: 0 },
    { id: 34, ingles: '¿Cómo se dice "beige"?',                espanol: 'Traducción al inglés',                   opciones: ['Beige', 'Cream', 'White'],                                        correcta: 0 },
    { id: 35, ingles: 'You are describing a rainbow. You say:',  espanol: 'Describes un arcoíris. Dices:',         opciones: ['A rainbow has many colors!', 'A rainbow is square!', 'A rainbow has five sides!'], correcta: 0 },
    { id: 36, ingles: 'What ___ is the sun?',                   espanol: '¿De qué ___ es el sol?',                opciones: ['color', 'shape', 'size'],                                         correcta: 0 },
    { id: 37, ingles: '¿Cómo se dice "cyan" o "celeste"?',     espanol: 'Traducción al inglés',                   opciones: ['Light blue', 'Dark blue', 'Turquoise'],                           correcta: 0 },
    { id: 38, ingles: 'Someone paints their house green. You say:', espanol: 'Alguien pinta su casa verde. Dices:', opciones: ['I love the green color!', 'I love the green triangle!', 'I love the green Monday!'], correcta: 0 },
    { id: 39, ingles: 'A pentagon has ___ sides.',              espanol: 'Un pentágono tiene ___ lados.',          opciones: ['five', 'six', 'four'],                                            correcta: 0 },
    { id: 40, ingles: '¿Cómo se dice "oliva"?',                espanol: 'Traducción al inglés',                   opciones: ['Olive', 'Dark green', 'Brown'],                                   correcta: 0 },
    { id: 41, ingles: 'The color of chocolate is ___.',         espanol: 'El color del chocolate es ___.',         opciones: ['brown', 'black', 'red'],                                          correcta: 0 },
    { id: 42, ingles: 'What shape is a wheel?',                 espanol: '¿Qué forma tiene una rueda?',            opciones: ['Circle', 'Square', 'Rectangle'],                                  correcta: 0 },
    { id: 43, ingles: '¿Cómo se dice "violeta"?',              espanol: 'Traducción al inglés',                   opciones: ['Violet', 'Purple', 'Lavender'],                                   correcta: 0 },
    { id: 44, ingles: 'You need a warm color for your room. You choose:', espanol: 'Necesitas un color cálido para tu cuarto. Eliges:', opciones: ['Orange or yellow', 'Blue or green', 'Black or gray'], correcta: 0 },
    { id: 45, ingles: 'A hexagon has ___ sides.',               espanol: 'Un hexágono tiene ___ lados.',           opciones: ['six', 'five', 'seven'],                                           correcta: 0 },
    { id: 46, ingles: '¿Cómo se dice "índigo"?',               espanol: 'Traducción al inglés',                   opciones: ['Indigo', 'Dark blue', 'Violet'],                                  correcta: 0 },
    { id: 47, ingles: 'What color is a flamingo?',              espanol: '¿De qué color es un flamenco?',          opciones: ['Pink', 'Red', 'Orange'],                                          correcta: 0 },
    { id: 48, ingles: 'The shape of a slice of pizza is a ___.',espanol: 'La forma de una porción de pizza es un ___.', opciones: ['triangle', 'circle', 'square'],                               correcta: 0 },
    { id: 49, ingles: '¿Cómo se dice "color primario"?',       espanol: 'Traducción al inglés',                   opciones: ['Primary color', 'First color', 'Main color'],                     correcta: 0 },
    { id: 50, ingles: 'You describe your favorite color. You say:', espanol: 'Describes tu color favorito. Dices:', opciones: ['My favorite color is blue because it reminds me of the sky.', 'My favorite color is Monday.', 'My favorite color is square.'], correcta: 0 },
  ],

  // Tema 4: El alfabeto
  4: [

    { id: 1,  ingles: 'Which letter comes after "B"?',          espanol: '¿Qué letra viene después de "B"?',       opciones: ['A', 'C', 'D'],                                                    correcta: 1 },
    { id: 2,  ingles: 'How do you spell "cat"?',                espanol: '¿Cómo se deletrea "cat"?',               opciones: ['C-A-T', 'K-A-T', 'C-A-D'],                                       correcta: 0 },
    { id: 3,  ingles: 'Which letter is a vowel?',               espanol: '¿Cuál letra es una vocal?',              opciones: ['B', 'E', 'T'],                                                    correcta: 1 },
    { id: 4,  ingles: 'What is the first letter of the alphabet?', espanol: '¿Cuál es la primera letra del alfabeto?', opciones: ['A', 'Z', 'M'],                                              correcta: 0 },
    { id: 5,  ingles: 'What is the last letter of the alphabet?', espanol: '¿Cuál es la última letra del alfabeto?', opciones: ['Y', 'X', 'Z'],                                               correcta: 2 },
    { id: 6,  ingles: 'How many letters are in the English alphabet?', espanol: '¿Cuántas letras tiene el alfabeto inglés?', opciones: ['26', '24', '28'],                                     correcta: 0 },
    { id: 7,  ingles: 'Someone asks you to spell your name. Your name is Ana. You say:', espanol: 'Te piden deletrear tu nombre. Te llamas Ana. Dices:', opciones: ['A-N-A', 'A-N-E', 'A-M-A'], correcta: 0 },
    { id: 8,  ingles: 'Which letter comes before "D"?',         espanol: '¿Qué letra viene antes de "D"?',         opciones: ['E', 'C', 'B'],                                                    correcta: 1 },
    { id: 9,  ingles: 'How do you spell "dog"?',                espanol: '¿Cómo se deletrea "dog"?',               opciones: ['D-O-G', 'D-O-C', 'D-A-G'],                                       correcta: 0 },
    { id: 10, ingles: 'How many vowels are in the English alphabet?', espanol: '¿Cuántas vocales tiene el alfabeto inglés?', opciones: ['5', '6', '4'],                                         correcta: 0 },
    { id: 11, ingles: 'Someone says a word slowly. You need to ___. ', espanol: 'Alguien dice una palabra lentamente. Necesitas ___.',  opciones: ['spell it out', 'draw it', 'sing it'],       correcta: 0 },
    { id: 12, ingles: 'The letter "Q" is usually followed by ___.',  espanol: 'La letra "Q" usualmente va seguida de ___.',  opciones: ['U', 'A', 'E'],                                         correcta: 0 },
    { id: 13, ingles: 'How do you spell "book"?',               espanol: '¿Cómo se deletrea "book"?',              opciones: ['B-O-O-K', 'B-U-K', 'B-O-K'],                                     correcta: 0 },
    { id: 14, ingles: 'Which of these is a consonant?',         espanol: '¿Cuál de estas es una consonante?',      opciones: ['T', 'A', 'E'],                                                    correcta: 0 },
    { id: 15, ingles: 'Which letter comes after "M"?',          espanol: '¿Qué letra viene después de "M"?',       opciones: ['L', 'N', 'O'],                                                    correcta: 1 },
    { id: 16, ingles: 'Someone asks "Can you spell that?" You spell W-A-T-E-R. The word is:', espanol: 'Alguien pregunta "¿Puedes deletrearlo?" Deletreas W-A-T-E-R. La palabra es:', opciones: ['Water', 'Winter', 'Wafer'], correcta: 0 },
    { id: 17, ingles: 'How do you spell "school"?',             espanol: '¿Cómo se deletrea "school"?',            opciones: ['S-C-H-O-O-L', 'S-K-O-L', 'S-C-O-L'],                            correcta: 0 },
    { id: 18, ingles: 'The vowels in English are ___.',          espanol: 'Las vocales en inglés son ___.',         opciones: ['A, E, I, O, U', 'A, B, C, D, E', 'B, C, D, F, G'],              correcta: 0 },
    { id: 19, ingles: 'Which letter comes after "W"?',          espanol: '¿Qué letra viene después de "W"?',       opciones: ['V', 'X', 'Y'],                                                    correcta: 1 },
    { id: 20, ingles: 'How do you spell "happy"?',              espanol: '¿Cómo se deletrea "happy"?',             opciones: ['H-A-P-P-Y', 'H-A-P-Y', 'H-E-P-P-Y'],                            correcta: 0 },
    { id: 21, ingles: 'Someone gives you their email. You need them to spell it. You say:', espanol: 'Alguien te da su email. Necesitas que lo deletree. Dices:', opciones: ['Could you spell that for me?', 'Could you sing that for me?', 'Could you draw that for me?'], correcta: 0 },
    { id: 22, ingles: 'How do you spell "friend"?',             espanol: '¿Cómo se deletrea "friend"?',            opciones: ['F-R-I-E-N-D', 'F-R-E-N-D', 'F-R-I-N-D'],                        correcta: 0 },
    { id: 23, ingles: 'Which letter is between "S" and "U"?',   espanol: '¿Qué letra está entre "S" y "U"?',      opciones: ['T', 'R', 'V'],                                                    correcta: 0 },
    { id: 24, ingles: 'The letter "Y" can sometimes act as a ___.',  espanol: 'La letra "Y" a veces actúa como una ___.',  opciones: ['vowel', 'number', 'consonant'],                          correcta: 0 },
    { id: 25, ingles: 'How do you spell "English"?',            espanol: '¿Cómo se deletrea "English"?',           opciones: ['E-N-G-L-I-S-H', 'E-N-G-L-I-C-H', 'I-N-G-L-I-S-H'],            correcta: 0 },
    { id: 26, ingles: 'Someone spells out C-H-A-I-R. What is the word?', espanol: 'Alguien deletrea C-H-A-I-R. ¿Cuál es la palabra?', opciones: ['Chair', 'Choir', 'Chain'],                   correcta: 0 },
    { id: 27, ingles: 'Which letter comes before "Z"?',         espanol: '¿Qué letra viene antes de "Z"?',         opciones: ['X', 'Y', 'W'],                                                    correcta: 1 },
    { id: 28, ingles: 'How do you spell "music"?',              espanol: '¿Cómo se deletrea "music"?',             opciones: ['M-U-S-I-C', 'M-U-Z-I-C', 'M-U-S-I-K'],                          correcta: 0 },
    { id: 29, ingles: 'The letter after "P" is ___.',           espanol: 'La letra después de "P" es ___.',        opciones: ['Q', 'R', 'O'],                                                    correcta: 0 },
    { id: 30, ingles: 'How do you spell "beautiful"?',          espanol: '¿Cómo se deletrea "beautiful"?',         opciones: ['B-E-A-U-T-I-F-U-L', 'B-E-U-T-I-F-U-L', 'B-E-A-T-I-F-U-L'],   correcta: 0 },
    { id: 31, ingles: 'You hear the word "knight". How is it spelled?', espanol: 'Escuchas la palabra "knight". ¿Cómo se escribe?', opciones: ['K-N-I-G-H-T', 'N-I-G-H-T', 'K-N-I-T'],        correcta: 0 },
    { id: 32, ingles: 'Which letter is the 13th in the alphabet?', espanol: '¿Cuál es la 13ª letra del alfabeto?', opciones: ['M', 'N', 'L'],                                                   correcta: 0 },
    { id: 33, ingles: 'How do you spell "language"?',           espanol: '¿Cómo se deletrea "language"?',          opciones: ['L-A-N-G-U-A-G-E', 'L-A-N-G-A-G-E', 'L-E-N-G-U-A-G-E'],       correcta: 0 },
    { id: 34, ingles: 'Someone asks how to spell "world". You say:', espanol: 'Alguien pregunta cómo se deletrea "world". Dices:', opciones: ['W-O-R-L-D', 'W-U-R-L-D', 'W-O-R-D'],           correcta: 0 },
    { id: 35, ingles: 'The letter "_" comes between N and P.',  espanol: 'La letra "___ " está entre N y P.',      opciones: ['O', 'M', 'Q'],                                                    correcta: 0 },
    { id: 36, ingles: 'How do you spell "conversation"?',       espanol: '¿Cómo se deletrea "conversation"?',      opciones: ['C-O-N-V-E-R-S-A-T-I-O-N', 'C-O-N-V-E-R-S-I-O-N', 'C-O-N-V-A-R-S-A-T-I-O-N'], correcta: 0 },
    { id: 37, ingles: 'You need to write your email address. You spell it letter by ___.',  espanol: 'Debes escribir tu email. Lo deletreas letra por ___.',  opciones: ['letter', 'number', 'word'], correcta: 0 },
    { id: 38, ingles: 'Which letter is the 20th in the alphabet?', espanol: '¿Cuál es la 20ª letra del alfabeto?', opciones: ['T', 'S', 'U'],                                                   correcta: 0 },
    { id: 39, ingles: 'How do you spell "pronunciation"?',      espanol: '¿Cómo se deletrea "pronunciation"?',     opciones: ['P-R-O-N-U-N-C-I-A-T-I-O-N', 'P-R-O-N-O-U-N-C-I-A-T-I-O-N', 'P-R-E-N-U-N-C-I-A-T-I-O-N'], correcta: 0 },
    { id: 40, ingles: 'Someone spells T-E-A-C-H-E-R. What is the word?', espanol: 'Alguien deletrea T-E-A-C-H-E-R. ¿Cuál es la palabra?', opciones: ['Teacher', 'Theater', 'Teaser'],         correcta: 0 },
    { id: 41, ingles: 'Which letter is the 7th in the alphabet?', espanol: '¿Cuál es la 7ª letra del alfabeto?',   opciones: ['G', 'H', 'F'],                                                    correcta: 0 },
    { id: 42, ingles: 'How do you spell "alphabet"?',           espanol: '¿Cómo se deletrea "alphabet"?',          opciones: ['A-L-P-H-A-B-E-T', 'A-L-F-A-B-E-T', 'A-L-P-H-A-B-I-T'],       correcta: 0 },
    { id: 43, ingles: 'The letters "ch" in English usually make the sound in ___.',  espanol: 'Las letras "ch" en inglés suenan como en ___.', opciones: ['chair', 'school', 'character'],      correcta: 0 },
    { id: 44, ingles: 'How do you spell "knowledge"?',          espanol: '¿Cómo se deletrea "knowledge"?',         opciones: ['K-N-O-W-L-E-D-G-E', 'N-O-W-L-E-D-G-E', 'K-N-O-L-E-D-G-E'],  correcta: 0 },
    { id: 45, ingles: 'Someone asks you to spell your last name. It is Lopez. You say:', espanol: 'Te piden deletrear tu apellido. Es Lopez. Dices:', opciones: ['L-O-P-E-Z', 'L-O-P-E-S', 'L-U-P-E-Z'], correcta: 0 },
    { id: 46, ingles: 'Which two letters look the same but are different cases?', espanol: '¿Qué dos letras se ven igual pero en diferente caso?', opciones: ['C and c', 'A and a', 'S and s'], correcta: 0 },
    { id: 47, ingles: 'How do you spell "exercise"?',           espanol: '¿Cómo se deletrea "exercise"?',          opciones: ['E-X-E-R-C-I-S-E', 'E-X-E-R-S-I-S-E', 'E-X-E-R-C-I-Z-E'],    correcta: 0 },
    { id: 48, ingles: 'What letter comes before "G"?',          espanol: '¿Qué letra viene antes de "G"?',         opciones: ['F', 'H', 'E'],                                                    correcta: 0 },
    { id: 49, ingles: 'How do you spell "Wednesday"?',          espanol: '¿Cómo se deletrea "Wednesday"?',         opciones: ['W-E-D-N-E-S-D-A-Y', 'W-E-N-S-D-A-Y', 'W-E-D-N-E-Z-D-A-Y'],  correcta: 0 },
    { id: 50, ingles: 'You are on a call and need to confirm a code: B-7-K-2. You read:', espanol: 'En una llamada confirmas un código: B-7-K-2. Lees:', opciones: ['B as in Bravo, 7, K as in Kilo, 2', 'Beta 7 Kappa 2', 'B 7 K 2 please'], correcta: 0 },
  ],

  // Tema 5: Verbos básicos
  5: [

    { id: 1,  ingles: 'I ___ a student.',                        espanol: 'Yo ___ un estudiante.',                  opciones: ['am', 'have', 'go'],                                               correcta: 0 },
    { id: 2,  ingles: 'She ___ two brothers.',                   espanol: 'Ella ___ dos hermanos.',                 opciones: ['is', 'has', 'does'],                                              correcta: 1 },
    { id: 3,  ingles: 'They ___ to school every day.',           espanol: 'Ellos ___ a la escuela todos los días.', opciones: ['go', 'has', 'am'],                                                correcta: 0 },
    { id: 4,  ingles: 'What do you ___ for breakfast?',          espanol: '¿Qué ___ en el desayuno?',              opciones: ['have', 'go', 'is'],                                               correcta: 0 },
    { id: 5,  ingles: 'He ___ his homework now.',                espanol: 'Él ___ su tarea ahora.',                 opciones: ['does', 'go', 'have'],                                             correcta: 0 },
    { id: 6,  ingles: '¿Cómo se dice "correr"?',                espanol: 'Traducción al inglés',                   opciones: ['To run', 'To walk', 'To jump'],                                   correcta: 0 },
    { id: 7,  ingles: 'Someone asks what you do on weekends. You say:', espanol: 'Preguntan qué haces los fines de semana. Dices:', opciones: ['I play soccer and watch movies.', 'I am soccer and movies.', 'I soccer and movies.'], correcta: 0 },
    { id: 8,  ingles: 'We ___ English at school.',               espanol: 'Nosotros ___ inglés en la escuela.',     opciones: ['study', 'studies', 'studying'],                                   correcta: 0 },
    { id: 9,  ingles: '¿Cómo se dice "escribir"?',              espanol: 'Traducción al inglés',                   opciones: ['To write', 'To read', 'To speak'],                                correcta: 0 },
    { id: 10, ingles: 'She ___ to music every morning.',         espanol: 'Ella ___ música todas las mañanas.',     opciones: ['listens', 'listen', 'listening'],                                  correcta: 0 },
    { id: 11, ingles: 'Someone asks "Can you swim?" You reply:', espanol: 'Alguien pregunta "¿Sabes nadar?" Respondes:', opciones: ['Yes, I can swim very well!', 'Yes, I am swim.', 'Yes, I swimming.'], correcta: 0 },
    { id: 12, ingles: 'I ___ coffee every morning.',             espanol: 'Yo ___ café todas las mañanas.',         opciones: ['drink', 'drinks', 'drinking'],                                    correcta: 0 },
    { id: 13, ingles: '¿Cómo se dice "hablar"?',                espanol: 'Traducción al inglés',                   opciones: ['To speak', 'To listen', 'To read'],                               correcta: 0 },
    { id: 14, ingles: 'He ___ to the gym three times a week.',   espanol: 'Él ___ al gimnasio tres veces por semana.', opciones: ['goes', 'go', 'going'],                                        correcta: 0 },
    { id: 15, ingles: 'Someone invites you to eat. You say:',    espanol: 'Alguien te invita a comer. Dices:',      opciones: ['I would love to eat with you!', 'I am food.', 'I go food.'],      correcta: 0 },
    { id: 16, ingles: 'They ___ football in the park.',          espanol: 'Ellos ___ fútbol en el parque.',         opciones: ['play', 'plays', 'playing'],                                       correcta: 0 },
    { id: 17, ingles: '¿Cómo se dice "dormir"?',                espanol: 'Traducción al inglés',                   opciones: ['To sleep', 'To eat', 'To rest'],                                  correcta: 0 },
    { id: 18, ingles: 'She ___ her homework after school.',      espanol: 'Ella ___ su tarea después de la escuela.', opciones: ['does', 'do', 'doing'],                                         correcta: 0 },
    { id: 19, ingles: 'What ___ you do for fun?',               espanol: '¿Qué ___ para divertirte?',              opciones: ['do', 'does', 'are'],                                              correcta: 0 },
    { id: 20, ingles: '¿Cómo se dice "cocinar"?',               espanol: 'Traducción al inglés',                   opciones: ['To cook', 'To eat', 'To buy'],                                    correcta: 0 },
    { id: 21, ingles: 'Someone asks if you like reading. You say:', espanol: 'Alguien pregunta si te gusta leer. Dices:', opciones: ['Yes, I love reading novels!', 'Yes, I am reading.', 'Yes, I reads.'], correcta: 0 },
    { id: 22, ingles: 'I ___ my teeth every morning and night.', espanol: 'Yo ___ mis dientes cada mañana y noche.', opciones: ['brush', 'brushes', 'brushing'],                                 correcta: 0 },
    { id: 23, ingles: '¿Cómo se dice "aprender"?',              espanol: 'Traducción al inglés',                   opciones: ['To learn', 'To teach', 'To study'],                               correcta: 0 },
    { id: 24, ingles: 'He ___ his lunch at noon.',               espanol: 'Él ___ su almuerzo al mediodía.',        opciones: ['eats', 'eat', 'eating'],                                          correcta: 0 },
    { id: 25, ingles: 'Someone asks what sport you play. You say:', espanol: 'Preguntan qué deporte practicas. Dices:', opciones: ['I play basketball twice a week.', 'I am basketball.', 'I basketball twice.'], correcta: 0 },
    { id: 26, ingles: 'We ___ our grandparents on Sundays.',     espanol: 'Nosotros ___ a nuestros abuelos los domingos.', opciones: ['visit', 'visits', 'visiting'],                             correcta: 0 },
    { id: 27, ingles: '¿Cómo se dice "trabajar"?',              espanol: 'Traducción al inglés',                   opciones: ['To work', 'To play', 'To run'],                                   correcta: 0 },
    { id: 28, ingles: 'She ___ English and French.',             espanol: 'Ella ___ inglés y francés.',             opciones: ['speaks', 'speak', 'speaking'],                                    correcta: 0 },
    { id: 29, ingles: 'Someone asks about your hobbies. You reply:', espanol: 'Preguntan sobre tus pasatiempos. Respondes:', opciones: ['I enjoy cooking and painting.', 'I am hobby.', 'I hobby cooking.'], correcta: 0 },
    { id: 30, ingles: 'I ___ my friends at the coffee shop.',    espanol: 'Yo ___ a mis amigos en la cafetería.',   opciones: ['meet', 'meets', 'meeting'],                                       correcta: 0 },
    { id: 31, ingles: '¿Cómo se dice "viajar"?',                espanol: 'Traducción al inglés',                   opciones: ['To travel', 'To walk', 'To fly'],                                 correcta: 0 },
    { id: 32, ingles: 'He ___ the newspaper in the morning.',    espanol: 'Él ___ el periódico en la mañana.',      opciones: ['reads', 'read', 'reading'],                                       correcta: 0 },
    { id: 33, ingles: 'Someone says they want to practice English. You say:', espanol: 'Alguien dice que quiere practicar inglés. Dices:', opciones: ['That is great! Let us practice together!', 'That is blue!', 'That is Monday!'], correcta: 0 },
    { id: 34, ingles: 'We ___ a lot of water every day.',        espanol: 'Nosotros ___ mucha agua todos los días.', opciones: ['drink', 'drinks', 'drinking'],                                  correcta: 0 },
    { id: 35, ingles: '¿Cómo se dice "caminar"?',               espanol: 'Traducción al inglés',                   opciones: ['To walk', 'To run', 'To jump'],                                   correcta: 0 },
    { id: 36, ingles: 'She ___ yoga on Tuesdays.',               espanol: 'Ella ___ yoga los martes.',              opciones: ['does', 'do', 'doing'],                                            correcta: 0 },
    { id: 37, ingles: 'Someone asks what you eat for lunch. You say:', espanol: 'Preguntan qué comes en el almuerzo. Dices:', opciones: ['I usually eat rice and chicken.', 'I usually am rice.', 'I usually rice.'], correcta: 0 },
    { id: 38, ingles: 'I ___ my dog for a walk every evening.',  espanol: 'Yo ___ a mi perro a caminar cada tarde.', opciones: ['take', 'takes', 'taking'],                                      correcta: 0 },
    { id: 39, ingles: '¿Cómo se dice "escuchar"?',              espanol: 'Traducción al inglés',                   opciones: ['To listen', 'To hear', 'To speak'],                               correcta: 0 },
    { id: 40, ingles: 'They ___ movies every weekend.',          espanol: 'Ellos ___ películas cada fin de semana.', opciones: ['watch', 'watches', 'watching'],                                  correcta: 0 },
    { id: 41, ingles: 'Someone asks what you do in your free time. You say:', espanol: 'Preguntan qué haces en tu tiempo libre. Dices:', opciones: ['I like to draw and listen to music.', 'I am free time.', 'I have free time music.'], correcta: 0 },
    { id: 42, ingles: 'He ___ chess with his father.',           espanol: 'Él ___ ajedrez con su padre.',           opciones: ['plays', 'play', 'playing'],                                       correcta: 0 },
    { id: 43, ingles: '¿Cómo se dice "cantar"?',                espanol: 'Traducción al inglés',                   opciones: ['To sing', 'To dance', 'To play'],                                 correcta: 0 },
    { id: 44, ingles: 'We ___ to the beach in the summer.',      espanol: 'Nosotros ___ a la playa en el verano.',  opciones: ['go', 'goes', 'going'],                                            correcta: 0 },
    { id: 45, ingles: 'Someone asks if you can drive. You say:', espanol: 'Preguntan si sabes manejar. Dices:',     opciones: ["Yes, I have had my license for two years.", "Yes, I am drive.", "Yes, I driving."], correcta: 0 },
    { id: 46, ingles: 'She ___ her friends every day.',          espanol: 'Ella ___ a sus amigos todos los días.',  opciones: ['texts', 'text', 'texting'],                                       correcta: 0 },
    { id: 47, ingles: '¿Cómo se dice "bailar"?',                espanol: 'Traducción al inglés',                   opciones: ['To dance', 'To sing', 'To jump'],                                 correcta: 0 },
    { id: 48, ingles: 'I ___ my best to learn English.',         espanol: 'Yo ___ mi mejor esfuerzo para aprender inglés.', opciones: ['do', 'does', 'doing'],                                  correcta: 0 },
    { id: 49, ingles: 'Someone asks if you exercise. You say:',  espanol: 'Preguntan si haces ejercicio. Dices:',   opciones: ['Yes, I run every morning.', 'Yes, I am exercise.', 'Yes, I exercising.'], correcta: 0 },
    { id: 50, ingles: 'He ___ his best friend every day at work.', espanol: 'Él ___ a su mejor amigo todos los días en el trabajo.', opciones: ['sees', 'see', 'seeing'],                      correcta: 0 },
  ],

  // ── NIVEL A1 en adelante ─────────────────────────────────────────────────
  // Tema 6: La familia
  6: [
    { id: 1, ingles: "What do you call your father's wife?", espanol: '¿Cómo le llamas a la esposa de tu padre?', opciones: ['My mother.', 'My sister.', 'My friend.'], correcta: 0 },
    { id: 2, ingles: "My father's brother is my...", espanol: 'El hermano de mi padre es mi...', opciones: ['cousin', 'uncle', 'grandfather'], correcta: 1 },
    { id: 3, ingles: 'How many siblings do you have?', espanol: '¿Cuántos hermanos tienes?', opciones: ['I have two siblings.', 'I am ten years old.', 'I live in Bogotá.'], correcta: 0 },
    { id: 4, ingles: "My parents' parents are my...", espanol: 'Los padres de mis padres son mis...', opciones: ['parents', 'grandparents', 'cousins'], correcta: 1 },
    { id: 5, ingles: "My sister's daughter is my...", espanol: 'La hija de mi hermana es mi...', opciones: ['niece', 'aunt', 'sister'], correcta: 0 },
  ],
  // Tema 7: Comida y bebidas
  7: [
    { id: 1, ingles: 'What is your favorite food?', espanol: '¿Cuál es tu comida favorita?', opciones: ['I like pizza.', 'I am pizza.', 'I have a chair.'], correcta: 0 },
    { id: 2, ingles: "I don't like vegetables.", espanol: 'No me gustan los vegetales.', opciones: ['I like vegetables a lot.', "I don't like vegetables.", 'I eat vegetables.'], correcta: 1 },
    { id: 3, ingles: 'What do you want to drink?', espanol: '¿Qué quieres tomar?', opciones: ['I want water, please.', 'I want a chair.', 'I am hungry.'], correcta: 0 },
    { id: 4, ingles: 'What did you have for breakfast?', espanol: '¿Qué desayunaste?', opciones: ['I had eggs and bread.', 'I go to school.', 'I am thirsty.'], correcta: 0 },
    { id: 5, ingles: 'How does the soup taste?', espanol: '¿Cómo sabe la sopa?', opciones: ['It is delicious!', 'It is fast!', 'It is tall!'], correcta: 0 },
  ],
  // Tema 8: La casa
  8: [
    { id: 1, ingles: 'Where do you cook your food?', espanol: '¿Dónde cocinas tu comida?', opciones: ['In the kitchen.', 'In the bedroom.', 'In the bathroom.'], correcta: 0 },
    { id: 2, ingles: 'Where do you sleep?', espanol: '¿Dónde duermes?', opciones: ['I sleep in the bedroom.', 'I sleep in the kitchen.', 'I sleep in the garage.'], correcta: 0 },
    { id: 3, ingles: 'We watch TV in the living room.', espanol: 'Vemos TV en la sala.', opciones: ['We watch TV in the bathroom.', 'We watch TV in the living room.', 'We eat in the bedroom.'], correcta: 1 },
    { id: 4, ingles: 'Is there a garden in your house?', espanol: '¿Hay un jardín en tu casa?', opciones: ['Yes, there is a garden.', 'Yes, I am hungry.', 'No, I sleep well.'], correcta: 0 },
    { id: 5, ingles: 'How many bedrooms does your house have?', espanol: '¿Cuántas habitaciones tiene tu casa?', opciones: ['My house has three bedrooms.', 'My house is blue.', 'My house is big.'], correcta: 0 },
  ],
  // Tema 9: Animales
  9: [
    { id: 1, ingles: 'What is the dog doing?', espanol: '¿Qué está haciendo el perro?', opciones: ['It is sleeping.', 'It is flying.', 'It is swimming.'], correcta: 0 },
    { id: 2, ingles: 'Which animal says "meow"?', espanol: '¿Qué animal dice "miau"?', opciones: ['Dog', 'Cat', 'Bird'], correcta: 1 },
    { id: 3, ingles: 'Which animal can fly?', espanol: '¿Qué animal puede volar?', opciones: ['Bird', 'Fish', 'Cow'], correcta: 0 },
    { id: 4, ingles: 'Do you have any pets?', espanol: '¿Tienes alguna mascota?', opciones: ['Yes, I have a dog.', 'Yes, I am tired.', 'No, I am happy.'], correcta: 0 },
    { id: 5, ingles: 'Which animal lives in water?', espanol: '¿Qué animal vive en el agua?', opciones: ['Fish', 'Horse', 'Bird'], correcta: 0 },
  ],
  // Tema 10: Verbos regulares
  10: [
    { id: 1, ingles: 'Yesterday, I ___ (work) all day.', espanol: 'Ayer, yo ___ (trabajé) todo el día.', opciones: ['worked', 'work', 'working'], correcta: 0 },
    { id: 2, ingles: 'They ___ (play) soccer last weekend.', espanol: 'Ellos ___ (jugaron) fútbol el fin de semana pasado.', opciones: ['play', 'played', 'plays'], correcta: 1 },
    { id: 3, ingles: 'She ___ (talk) to her friend yesterday.', espanol: 'Ella ___ (habló) con su amiga ayer.', opciones: ['talk', 'talks', 'talked'], correcta: 2 },
    { id: 4, ingles: 'We ___ (watch) a movie last night.', espanol: 'Nosotros ___ (vimos) una película anoche.', opciones: ['watched', 'watch', 'watching'], correcta: 0 },
    { id: 5, ingles: 'I ___ (clean) my room this morning.', espanol: 'Yo ___ (limpié) mi cuarto esta mañana.', opciones: ['clean', 'cleaned', 'cleans'], correcta: 1 },
  ],
  // Tema 11: El cuerpo humano
  11: [
    { id: 1, ingles: 'What do you use to see?', espanol: '¿Qué usas para ver?', opciones: ['My eyes.', 'My hands.', 'My ears.'], correcta: 0 },
    { id: 2, ingles: 'What hurts?', espanol: '¿Qué te duele?', opciones: ['My head.', 'My foot is happy.', 'My hand is blue.'], correcta: 0 },
    { id: 3, ingles: 'I have ten ___ on my hands.', espanol: 'Tengo diez ___ en mis manos.', opciones: ['feet', 'fingers', 'ears'], correcta: 1 },
    { id: 4, ingles: 'I hear with my...', espanol: 'Escucho con mis...', opciones: ['ears', 'eyes', 'nose'], correcta: 0 },
    { id: 5, ingles: 'I walk with my...', espanol: 'Camino con mis...', opciones: ['hands', 'feet', 'ears'], correcta: 1 },
  ],
  // Tema 12: Presente simple
  12: [
    { id: 1, ingles: 'She ___ to work every day.', espanol: 'Ella ___ al trabajo todos los días.', opciones: ['go', 'goes', 'going'], correcta: 1 },
    { id: 2, ingles: 'Do you like coffee?', espanol: '¿Te gusta el café?', opciones: ['Yes, I like it.', 'Yes, I am liking it.', 'Yes, I liked it.'], correcta: 0 },
    { id: 3, ingles: 'He ___ not speak French.', espanol: 'Él no habla francés.', opciones: ['do', 'does', 'is'], correcta: 1 },
    { id: 4, ingles: 'What time does the store open?', espanol: '¿A qué hora abre la tienda?', opciones: ['It opens at nine.', 'It opened at nine.', 'It is opening now.'], correcta: 0 },
    { id: 5, ingles: 'They ___ in Bogotá.', espanol: 'Ellos viven en Bogotá.', opciones: ['live', 'lives', 'living'], correcta: 0 },
  ],
  // Tema 13: Presente continuo
  13: [
    { id: 1, ingles: 'What are you doing right now?', espanol: '¿Qué estás haciendo en este momento?', opciones: ["I'm studying English.", 'I study English.', 'I studied English.'], correcta: 0 },
    { id: 2, ingles: 'She ___ a book at the moment.', espanol: 'Ella está leyendo un libro en este momento.', opciones: ['reads', 'is reading', 'read'], correcta: 1 },
    { id: 3, ingles: 'They ___ dinner right now.', espanol: 'Ellos están preparando la cena ahora mismo.', opciones: ['are cooking', 'cook', 'cooked'], correcta: 0 },
    { id: 4, ingles: 'Look! It ___ outside.', espanol: '¡Mira! Está lloviendo afuera.', opciones: ['rains', 'is raining', 'rained'], correcta: 1 },
    { id: 5, ingles: 'Why are you laughing?', espanol: '¿Por qué te estás riendo?', opciones: ['That joke was funny.', 'That joke is funny tomorrow.', 'That joke laughs.'], correcta: 0 },
  ],
  // Tema 14: Verbos irregulares básicos
  14: [
    { id: 1, ingles: 'Yesterday I ___ to the park.', espanol: 'Ayer fui al parque.', opciones: ['go', 'went', 'goes'], correcta: 1 },
    { id: 2, ingles: 'She ___ a great time at the party.', espanol: 'Ella tuvo un gran momento en la fiesta.', opciones: ['have', 'has', 'had'], correcta: 2 },
    { id: 3, ingles: 'We ___ a movie last night.', espanol: 'Vimos una película anoche.', opciones: ['saw', 'see', 'seen'], correcta: 0 },
    { id: 4, ingles: 'I ___ my keys this morning.', espanol: 'Perdí mis llaves esta mañana.', opciones: ['lose', 'lost', 'losed'], correcta: 1 },
    { id: 5, ingles: 'He ___ very happy when he heard the news.', espanol: 'Él se sintió muy feliz cuando escuchó la noticia.', opciones: ['feel', 'feeled', 'felt'], correcta: 2 },
  ],
  // Tema 15: Verbos modales básicos
  15: [
    { id: 1, ingles: 'I ___ swim very well.', espanol: 'Puedo nadar muy bien.', opciones: ['can', 'must', 'will'], correcta: 0 },
    { id: 2, ingles: "She ___ speak Japanese.", espanol: 'Ella no puede hablar japonés.', opciones: ["can't", "isn't", "doesn't"], correcta: 0 },
    { id: 3, ingles: '___ you help me with this bag?', espanol: '¿Podrías ayudarme con esta bolsa?', opciones: ['Could', 'Am', 'Do'], correcta: 0 },
    { id: 4, ingles: 'If I had more time, I ___ travel more.', espanol: 'Si tuviera más tiempo, viajaría más.', opciones: ['would', 'can', 'must'], correcta: 0 },
    { id: 5, ingles: 'You ___ be quiet, the baby is sleeping.', espanol: 'Debes estar callado, el bebé está durmiendo.', opciones: ['must', 'can', 'would'], correcta: 0 },
  ],
  // Tema 16: El tiempo y clima
  16: [
    { id: 1, ingles: "What's the weather like today?", espanol: '¿Cómo está el clima hoy?', opciones: ["It's sunny.", "It's Monday.", "It's blue."], correcta: 0 },
    { id: 2, ingles: 'Bring an umbrella, it might...', espanol: 'Trae una sombrilla, podría...', opciones: ['rain.', 'shine.', 'snow you.'], correcta: 0 },
    { id: 3, ingles: "It's very ___ today, wear a coat.", espanol: 'Está muy frío hoy, usa un abrigo.', opciones: ['cold', 'hot', 'sunny'], correcta: 0 },
    { id: 4, ingles: 'What season comes after winter?', espanol: '¿Qué estación viene después del invierno?', opciones: ['Spring', 'Summer', 'Fall'], correcta: 0 },
    { id: 5, ingles: 'I love walking in the snow.', espanol: 'Me encanta caminar en la nieve.', opciones: ['That sounds fun!', 'That sounds hungry!', 'That sounds tall!'], correcta: 0 },
  ],
  // Tema 17: Transporte y ciudad
  17: [
    { id: 1, ingles: 'Excuse me, where is the bus stop?', espanol: 'Disculpe, ¿dónde está la parada de autobús?', opciones: ["It's two blocks away.", "It's blue.", "It's Tuesday."], correcta: 0 },
    { id: 2, ingles: 'How do you get to work?', espanol: '¿Cómo llegas al trabajo?', opciones: ['I take the train.', 'I am the train.', 'I have a train.'], correcta: 0 },
    { id: 3, ingles: 'Is there a subway station nearby?', espanol: '¿Hay una estación de metro cerca?', opciones: ['Yes, right around the corner.', 'Yes, I am tired.', 'No, I like trains.'], correcta: 0 },
    { id: 4, ingles: "I'm lost. Can you help me?", espanol: 'Estoy perdido. ¿Puedes ayudarme?', opciones: ['Sure, where do you want to go?', 'Sure, what time is it?', 'Sure, I am hungry.'], correcta: 0 },
    { id: 5, ingles: 'The taxi will arrive in ten minutes.', espanol: 'El taxi llegará en diez minutos.', opciones: ['Great, I will wait outside.', 'Great, I ate breakfast.', 'Great, it is raining.'], correcta: 0 },
  ],
  // Tema 18: Compras y precios
  18: [
    { id: 1, ingles: 'How much is this shirt?', espanol: '¿Cuánto cuesta esta camisa?', opciones: ["It's twenty dollars.", "It's blue.", "It's Monday."], correcta: 0 },
    { id: 2, ingles: "I'd like to buy this, please.", espanol: 'Quisiera comprar esto, por favor.', opciones: ['Sure, follow me to the register.', 'Sure, I am tired.', 'Sure, it rains today.'], correcta: 0 },
    { id: 3, ingles: 'Do you accept credit cards?', espanol: '¿Aceptan tarjetas de crédito?', opciones: ['Yes, we do.', 'Yes, I am.', 'Yes, it does.'], correcta: 0 },
    { id: 4, ingles: 'This is too expensive for me.', espanol: 'Esto es muy caro para mí.', opciones: ['We have a cheaper option.', 'We have a blue option.', 'We have a tall option.'], correcta: 0 },
    { id: 5, ingles: 'Can I get a discount?', espanol: '¿Puedo obtener un descuento?', opciones: ['Yes, 10% off today.', 'Yes, I am happy.', 'Yes, it is raining.'], correcta: 0 },
  ],
  // Tema 19: Pasado simple vs. continuo
  19: [
    { id: 1, ingles: 'What were you doing when I called?', espanol: '¿Qué estabas haciendo cuando llamé?', opciones: ['I was watching a movie.', 'I watched a movie.', 'I watch a movie.'], correcta: 0 },
    { id: 2, ingles: 'She ___ when the lights went out.', espanol: 'Ella estaba leyendo cuando se fue la luz.', opciones: ['read', 'was reading', 'reads'], correcta: 1 },
    { id: 3, ingles: 'While he ___, the phone rang.', espanol: 'Mientras él dormía, sonó el teléfono.', opciones: ['slept', 'was sleeping', 'sleeps'], correcta: 1 },
    { id: 4, ingles: 'They arrived while we ___ dinner.', espanol: 'Llegaron mientras nosotros estábamos cenando.', opciones: ['had', 'were having', 'have'], correcta: 1 },
    { id: 5, ingles: 'I ___ a great book when you interrupted me.', espanol: 'Estaba leyendo un gran libro cuando me interrumpiste.', opciones: ['read', 'was reading', 'am reading'], correcta: 1 },
  ],
  // Tema 20: Presente perfecto
  20: [
    { id: 1, ingles: 'I ___ never been to Japan.', espanol: 'Nunca he estado en Japón.', opciones: ['have', 'had', 'has'], correcta: 0 },
    { id: 2, ingles: 'She has already ___ her homework.', espanol: 'Ella ya ha terminado su tarea.', opciones: ['finish', 'finished', 'finishing'], correcta: 1 },
    { id: 3, ingles: 'Have you ever tried sushi?', espanol: '¿Alguna vez has probado el sushi?', opciones: ['Yes, I have tried it once.', 'Yes, I tried it tomorrow.', 'Yes, I try it now.'], correcta: 0 },
    { id: 4, ingles: 'They ___ just arrived at the hotel.', espanol: 'Ellos acaban de llegar al hotel.', opciones: ['have', 'had', 'are'], correcta: 0 },
    { id: 5, ingles: 'How long have you lived in Bogotá?', espanol: '¿Cuánto tiempo llevas viviendo en Bogotá?', opciones: ['I have lived here for five years.', 'I live here tomorrow.', 'I lived here yesterday.'], correcta: 0 },
  ],
  // Tema 21: Futuro (will / going to)
  21: [
    { id: 1, ingles: 'I think it ___ rain tomorrow.', espanol: 'Creo que mañana va a llover.', opciones: ['will', 'is', 'was'], correcta: 0 },
    { id: 2, ingles: 'We ___ going to visit my grandparents this weekend.', espanol: 'Vamos a visitar a mis abuelos este fin de semana.', opciones: ['are', 'were', 'have'], correcta: 0 },
    { id: 3, ingles: 'Look at those clouds! It ___ going to rain.', espanol: '¡Mira esas nubes! Va a llover.', opciones: ['is', 'was', 'will'], correcta: 0 },
    { id: 4, ingles: 'I promise I ___ call you later.', espanol: 'Te prometo que te llamaré más tarde.', opciones: ['will', 'am going to', 'would'], correcta: 0 },
    { id: 5, ingles: 'She ___ going to study medicine next year.', espanol: 'Ella va a estudiar medicina el próximo año.', opciones: ['is', 'are', 'was'], correcta: 0 },
  ],
  // Tema 22: Condicionales (tipo 1 y 2)
  22: [
    { id: 1, ingles: 'If it rains, we ___ stay home.', espanol: 'Si llueve, nos quedaremos en casa.', opciones: ['will', 'would', 'are'], correcta: 0 },
    { id: 2, ingles: 'If I won the lottery, I ___ travel the world.', espanol: 'Si ganara la lotería, viajaría por el mundo.', opciones: ['would', 'will', 'am going to'], correcta: 0 },
    { id: 3, ingles: 'She will pass the exam if she ___.', espanol: 'Ella pasará el examen si estudia.', opciones: ['studies', 'studied', 'would study'], correcta: 0 },
    { id: 4, ingles: 'If I ___ you, I would apologize.', espanol: 'Si yo fuera tú, pediría disculpas.', opciones: ['were', 'am', 'was'], correcta: 0 },
    { id: 5, ingles: 'What would you do if you ___ a superpower?', espanol: '¿Qué harías si tuvieras un superpoder?', opciones: ['had', 'have', 'will have'], correcta: 0 },
  ],
  // Tema 23: Vocabulario de trabajo y profesiones
  23: [
    { id: 1, ingles: 'What do you do for a living?', espanol: '¿A qué te dedicas?', opciones: ['I am a software engineer.', 'I am a software.', 'I do a software.'], correcta: 0 },
    { id: 2, ingles: 'A person who treats sick people is a...', espanol: 'Una persona que trata a enfermos es un...', opciones: ['doctor', 'lawyer', 'chef'], correcta: 0 },
    { id: 3, ingles: 'I have a job interview tomorrow.', espanol: 'Tengo una entrevista de trabajo mañana.', opciones: ['Good luck, I hope it goes well!', 'Good luck, I am hungry!', 'Good luck, it is raining!'], correcta: 0 },
    { id: 4, ingles: 'She works ___ a teacher at a local school.', espanol: 'Ella trabaja como maestra en una escuela local.', opciones: ['as', 'like', 'for'], correcta: 0 },
    { id: 5, ingles: 'My boss gave me a promotion last month.', espanol: 'Mi jefe me dio un ascenso el mes pasado.', opciones: ['That is great news!', 'That is very cold!', 'That is very blue!'], correcta: 0 },
  ],
  // Tema 24: Salud y el médico
  24: [
    { id: 1, ingles: "I don't feel well. I have a headache.", espanol: 'No me siento bien. Tengo dolor de cabeza.', opciones: ['You should rest and drink water.', 'You should go dancing.', 'You should eat more sugar.'], correcta: 0 },
    { id: 2, ingles: 'What are your symptoms?', espanol: '¿Cuáles son tus síntomas?', opciones: ['I have a fever and a sore throat.', 'I have a car and a house.', 'I have a pen and a book.'], correcta: 0 },
    { id: 3, ingles: 'The doctor ___ me to take this medicine twice a day.', espanol: 'El médico me dijo que tomara este medicamento dos veces al día.', opciones: ['told', 'said', 'asked'], correcta: 0 },
    { id: 4, ingles: 'I need to make an appointment with the dentist.', espanol: 'Necesito hacer una cita con el dentista.', opciones: ['I can help you find their number.', 'I can help you find their car.', 'I can help you find their dog.'], correcta: 0 },
    { id: 5, ingles: 'How long have you had this pain?', espanol: '¿Hace cuánto tiempo tienes este dolor?', opciones: ['Since yesterday morning.', 'Since I am hungry.', 'Since it is blue.'], correcta: 0 },
  ],
  // Tema 25: Viajes y turismo
  25: [
    { id: 1, ingles: 'I would like to book a room for two nights.', espanol: 'Quisiera reservar una habitación por dos noches.', opciones: ['Of course! Single or double?', 'Of course! Hot or cold?', 'Of course! Big or blue?'], correcta: 0 },
    { id: 2, ingles: 'Where is the nearest tourist information center?', espanol: '¿Dónde está el centro de información turística más cercano?', opciones: ["It's just down the street.", "It's just down the river.", "It's very hungry."], correcta: 0 },
    { id: 3, ingles: 'My flight was delayed by two hours.', espanol: 'Mi vuelo se retrasó dos horas.', opciones: ['That is frustrating. Did you get a voucher?', 'That is delicious. Did you eat?', 'That is blue. Did you see?'], correcta: 0 },
    { id: 4, ingles: 'Do I need a visa to travel to Canada?', espanol: '¿Necesito visa para viajar a Canadá?', opciones: ['It depends on your passport.', 'It depends on your food.', 'It depends on your color.'], correcta: 0 },
    { id: 5, ingles: 'What is the most popular attraction here?', espanol: '¿Cuál es la atracción más popular aquí?', opciones: ['The old cathedral is a must-see.', 'The old cathedral is very hungry.', 'The old cathedral is very fast.'], correcta: 0 },
  ],
  // Tema 26: Emociones y sentimientos
  26: [
    { id: 1, ingles: 'How do you feel when you achieve a goal?', espanol: '¿Cómo te sientes cuando logras una meta?', opciones: ['I feel proud and happy.', 'I feel blue and square.', 'I feel hungry and tall.'], correcta: 0 },
    { id: 2, ingles: 'She looked ___ when she heard the bad news.', espanol: 'Ella se veía devastada cuando escuchó las malas noticias.', opciones: ['devastated', 'delicious', 'fast'], correcta: 0 },
    { id: 3, ingles: 'I get nervous when I have to speak in public.', espanol: 'Me pongo nervioso cuando tengo que hablar en público.', opciones: ['That is very common, you can practice!', 'That is very cold, wear a coat!', 'That is very tall, be careful!'], correcta: 0 },
    { id: 4, ingles: 'He was ___ because he missed the bus.', espanol: 'Él estaba frustrado porque perdió el autobús.', opciones: ['frustrated', 'delighted', 'excited'], correcta: 0 },
    { id: 5, ingles: 'What makes you feel anxious?', espanol: '¿Qué te hace sentir ansioso?', opciones: ['Exams and tight deadlines make me anxious.', 'Exams and pizza make me tall.', 'Exams and weather make me blue.'], correcta: 0 },
  ],
  // Tema 27: Medio ambiente
  27: [
    { id: 1, ingles: 'We should recycle to protect the environment.', espanol: 'Debemos reciclar para proteger el medio ambiente.', opciones: ['I totally agree, every little bit helps.', 'I totally agree, it is very cold.', 'I totally agree, it is very blue.'], correcta: 0 },
    { id: 2, ingles: 'Climate change is causing more extreme weather events.', espanol: 'El cambio climático está causando eventos climáticos más extremos.', opciones: ['That is why we need to reduce emissions.', 'That is why we need to eat more.', 'That is why we need to sleep more.'], correcta: 0 },
    { id: 3, ingles: 'What can we do to save water at home?', espanol: '¿Qué podemos hacer para ahorrar agua en casa?', opciones: ['We can take shorter showers.', 'We can take longer naps.', 'We can take more food.'], correcta: 0 },
    { id: 4, ingles: 'Deforestation is destroying natural habitats.', espanol: 'La deforestación está destruyendo los hábitats naturales.', opciones: ['We need to plant more trees to help.', 'We need to eat more trees to help.', 'We need to paint more trees to help.'], correcta: 0 },
    { id: 5, ingles: 'Solar energy is a clean ___ of power.', espanol: 'La energía solar es una fuente limpia de energía.', opciones: ['source', 'color', 'flavor'], correcta: 0 },
  ],
  // Tema 28: Pasado perfecto
  28: [
    { id: 1, ingles: 'By the time she arrived, we ___ already eaten.', espanol: 'Cuando ella llegó, ya habíamos comido.', opciones: ['had', 'have', 'were'], correcta: 0 },
    { id: 2, ingles: 'He failed the exam because he ___ not studied.', espanol: 'Reprobó el examen porque no había estudiado.', opciones: ['had', 'has', 'was'], correcta: 0 },
    { id: 3, ingles: 'They realized they ___ taken the wrong train.', espanol: 'Se dieron cuenta de que habían tomado el tren equivocado.', opciones: ['had', 'have', 'did'], correcta: 0 },
    { id: 4, ingles: 'I was tired because I ___ worked all night.', espanol: 'Estaba cansado porque había trabajado toda la noche.', opciones: ['had', 'have', 'did'], correcta: 0 },
    { id: 5, ingles: 'She looked familiar. I felt I ___ seen her before.', espanol: 'Ella me parecía conocida. Sentía que la había visto antes.', opciones: ['had', 'have', 'was'], correcta: 0 },
  ],
  // Tema 29: Voz pasiva
  29: [
    { id: 1, ingles: 'The report ___ written by the manager.', espanol: 'El informe fue escrito por el gerente.', opciones: ['was', 'is', 'were'], correcta: 0 },
    { id: 2, ingles: 'English ___ spoken all over the world.', espanol: 'El inglés se habla en todo el mundo.', opciones: ['is', 'was', 'are'], correcta: 0 },
    { id: 3, ingles: 'The windows ___ cleaned yesterday.', espanol: 'Las ventanas fueron limpiadas ayer.', opciones: ['were', 'are', 'have'], correcta: 0 },
    { id: 4, ingles: 'The new building ___ being constructed right now.', espanol: 'El nuevo edificio está siendo construido ahora mismo.', opciones: ['is', 'was', 'were'], correcta: 0 },
    { id: 5, ingles: 'The package will ___ delivered tomorrow.', espanol: 'El paquete será entregado mañana.', opciones: ['be', 'been', 'being'], correcta: 0 },
  ],
  // Tema 30: Discurso indirecto
  30: [
    { id: 1, ingles: 'She said she ___ tired.', espanol: 'Ella dijo que estaba cansada.', opciones: ['was', 'is', 'were'], correcta: 0 },
    { id: 2, ingles: 'He told me he ___ call me the next day.', espanol: 'Él me dijo que me llamaría al día siguiente.', opciones: ['would', 'will', 'could'], correcta: 0 },
    { id: 3, ingles: 'They said they ___ been to Paris before.', espanol: 'Dijeron que habían estado en París antes.', opciones: ['had', 'have', 'were'], correcta: 0 },
    { id: 4, ingles: 'The teacher told us ___ quiet during the test.', espanol: 'La maestra nos dijo que estuviéramos callados durante el examen.', opciones: ['to be', 'being', 'be'], correcta: 0 },
    { id: 5, ingles: 'She asked me where I ___.', espanol: 'Ella me preguntó dónde vivía.', opciones: ['lived', 'live', 'was living'], correcta: 0 },
  ],
  // Tema 31: Conectores y cohesión
  31: [
    { id: 1, ingles: 'I wanted to go out; ___, it was raining hard.', espanol: 'Quería salir; sin embargo, llovía mucho.', opciones: ['however', 'therefore', 'besides'], correcta: 0 },
    { id: 2, ingles: 'She studied hard. ___, she passed the exam.', espanol: 'Estudió mucho. Por lo tanto, pasó el examen.', opciones: ['Therefore', 'Although', 'Unless'], correcta: 0 },
    { id: 3, ingles: '___ he is rich, he is not happy.', espanol: 'Aunque es rico, no es feliz.', opciones: ['Although', 'Therefore', 'Besides'], correcta: 0 },
    { id: 4, ingles: 'You will fail ___ you study more.', espanol: 'Vas a reprobar a menos que estudies más.', opciones: ['unless', 'although', 'however'], correcta: 0 },
    { id: 5, ingles: 'He is smart. ___, he works very hard.', espanol: 'Es inteligente. Además, trabaja muy duro.', opciones: ['Moreover', 'Unless', 'Although'], correcta: 0 },
  ],
  // Tema 32: Tecnología y redes sociales
  32: [
    { id: 1, ingles: 'How often do you use social media?', espanol: '¿Con qué frecuencia usas las redes sociales?', opciones: ['I check it several times a day.', 'I check it with food.', 'I check it with rain.'], correcta: 0 },
    { id: 2, ingles: 'My phone ___ out of battery. Can I charge it here?', espanol: 'Mi teléfono se quedó sin batería. ¿Puedo cargarlo aquí?', opciones: ['ran', 'run', 'runs'], correcta: 0 },
    { id: 3, ingles: 'You should update your password regularly for security.', espanol: 'Deberías actualizar tu contraseña regularmente por seguridad.', opciones: ['That is good advice, I will do it now.', 'That is good food, I will eat now.', 'That is good weather, I will go now.'], correcta: 0 },
    { id: 4, ingles: 'Artificial intelligence is changing many industries.', espanol: 'La inteligencia artificial está cambiando muchas industrias.', opciones: ['It is both exciting and challenging.', 'It is both hungry and cold.', 'It is both blue and tall.'], correcta: 0 },
    { id: 5, ingles: 'Can you ___ me that file by email?', espanol: '¿Puedes enviarme ese archivo por correo electrónico?', opciones: ['send', 'say', 'tell'], correcta: 0 },
  ],
  // Tema 33: Cultura y arte
  33: [
    { id: 1, ingles: 'What kind of music do you enjoy?', espanol: '¿Qué tipo de música disfrutas?', opciones: ['I enjoy jazz and classical music.', 'I enjoy cars and buildings.', 'I enjoy rain and cold.'], correcta: 0 },
    { id: 2, ingles: 'This painting was created in the Renaissance period.', espanol: 'Esta pintura fue creada en el período del Renacimiento.', opciones: ['That is fascinating. Who painted it?', 'That is fascinating. Who ate it?', 'That is fascinating. Who drove it?'], correcta: 0 },
    { id: 3, ingles: 'The film received excellent ___ from critics.', espanol: 'La película recibió excelentes críticas.', opciones: ['reviews', 'recipes', 'weather'], correcta: 0 },
    { id: 4, ingles: 'Literature helps us understand different ___ of life.', espanol: 'La literatura nos ayuda a entender diferentes perspectivas de vida.', opciones: ['perspectives', 'ingredients', 'temperatures'], correcta: 0 },
    { id: 5, ingles: 'She plays the piano and also ___ in a choir.', espanol: 'Ella toca el piano y también canta en un coro.', opciones: ['sings', 'cooks', 'drives'], correcta: 0 },
  ],
  // Tema 34: Economía y finanzas personales
  34: [
    { id: 1, ingles: 'It is important to save a portion of your income every month.', espanol: 'Es importante ahorrar una parte de tus ingresos cada mes.', opciones: ['I agree, it helps for emergencies.', 'I agree, it helps for swimming.', 'I agree, it helps for painting.'], correcta: 0 },
    { id: 2, ingles: 'I need to pay my rent by the end of the month.', espanol: 'Necesito pagar mi alquiler al final del mes.', opciones: ['Set a reminder so you do not forget.', 'Set a color so you do not eat.', 'Set a rain so you do not sleep.'], correcta: 0 },
    { id: 3, ingles: 'What is the difference between a debit card and a credit card?', espanol: '¿Cuál es la diferencia entre una tarjeta débito y una de crédito?', opciones: ['A debit card uses your own money; credit is borrowed.', 'A debit card is blue; credit is red.', 'A debit card is hot; credit is cold.'], correcta: 0 },
    { id: 4, ingles: 'Investing early allows your money to ___ over time.', espanol: 'Invertir temprano permite que tu dinero crezca con el tiempo.', opciones: ['grow', 'sleep', 'fly'], correcta: 0 },
    { id: 5, ingles: 'I am trying to ___ my spending this month.', espanol: 'Estoy intentando reducir mis gastos este mes.', opciones: ['reduce', 'increase', 'paint'], correcta: 0 },
  ],
  // Tema 35: Argumentación y debate
  35: [
    { id: 1, ingles: 'In my opinion, education should be free for everyone.', espanol: 'En mi opinión, la educación debería ser gratuita para todos.', opciones: ['That is a valid point. What are your reasons?', 'That is a valid food. What do you eat?', 'That is a valid color. What do you see?'], correcta: 0 },
    { id: 2, ingles: 'I see your point, ___ I still disagree.', espanol: 'Entiendo tu punto, pero aún no estoy de acuerdo.', opciones: ['but', 'so', 'and'], correcta: 0 },
    { id: 3, ingles: 'On the one hand, technology saves time. On the other hand, it can be ___ .', espanol: 'Por un lado, la tecnología ahorra tiempo. Por otro lado, puede ser adictiva.', opciones: ['addictive', 'delicious', 'colorful'], correcta: 0 },
    { id: 4, ingles: 'Could you ___ your point with an example?', espanol: '¿Podrías apoyar tu punto con un ejemplo?', opciones: ['support', 'eat', 'paint'], correcta: 0 },
    { id: 5, ingles: 'To sum up, both sides have valid arguments.', espanol: 'En resumen, ambos lados tienen argumentos válidos.', opciones: ['That is a balanced conclusion.', 'That is a balanced recipe.', 'That is a balanced color.'], correcta: 0 },
  ],
  // Tema 36: Condicional tipo 3
  36: [
    { id: 1, ingles: 'If she had studied harder, she ___ passed the exam.', espanol: 'Si ella hubiera estudiado más, habría pasado el examen.', opciones: ['would have', 'would', 'had'], correcta: 0 },
    { id: 2, ingles: 'I ___ called you if I had known you were there.', espanol: 'Te habría llamado si hubiera sabido que estabas ahí.', opciones: ['would have', 'will have', 'had'], correcta: 0 },
    { id: 3, ingles: 'They would have won ___ they had practiced more.', espanol: 'Habrían ganado si hubieran practicado más.', opciones: ['if', 'unless', 'although'], correcta: 0 },
    { id: 4, ingles: 'If he had taken the job, his life ___ completely different.', espanol: 'Si hubiera aceptado el trabajo, su vida habría sido completamente diferente.', opciones: ['would have been', 'would be', 'had been'], correcta: 0 },
    { id: 5, ingles: "She ___ gotten lost if she had brought a map.", espanol: 'Ella no se habría perdido si hubiera traído un mapa.', opciones: ["wouldn't have", "wouldn't", "hadn't"], correcta: 0 },
  ],
  // Tema 37: Inversión y énfasis
  37: [
    { id: 1, ingles: 'Never ___ I seen such a beautiful sunset.', espanol: 'Nunca había visto un atardecer tan hermoso.', opciones: ['have', 'had', 'has'], correcta: 0 },
    { id: 2, ingles: 'Not only ___ she win, but she also broke the record.', espanol: 'No solo ganó, sino que también rompió el récord.', opciones: ['did', 'does', 'had'], correcta: 0 },
    { id: 3, ingles: 'Hardly ___ he sat down when the phone rang.', espanol: 'Apenas se había sentado cuando sonó el teléfono.', opciones: ['had', 'has', 'did'], correcta: 0 },
    { id: 4, ingles: 'What ___ impressed me was her confidence.', espanol: 'Lo que realmente me impresionó fue su confianza.', opciones: ['really', 'very', 'quite'], correcta: 0 },
    { id: 5, ingles: 'It was ___ the presentation that changed their minds.', espanol: 'Fue precisamente la presentación lo que cambió sus mentes.', opciones: ['precisely', 'barely', 'nearly'], correcta: 0 },
  ],
  // Tema 38: Verbos modales avanzados
  38: [
    { id: 1, ingles: 'She must ___ forgotten about the meeting.', espanol: 'Ella debe de haberse olvidado de la reunión.', opciones: ['have', 'had', 'be'], correcta: 0 },
    { id: 2, ingles: "He can't ___ done it on purpose.", espanol: 'No puede haberlo hecho a propósito.', opciones: ['have', 'had', 'be'], correcta: 0 },
    { id: 3, ingles: 'You should ___ told me earlier.', espanol: 'Deberías haberme dicho antes.', opciones: ['have', 'had', 'be'], correcta: 0 },
    { id: 4, ingles: 'They might ___ already left by the time we arrive.', espanol: 'Puede que ya hayan salido cuando lleguemos.', opciones: ['have', 'had', 'be'], correcta: 0 },
    { id: 5, ingles: "I needn't ___ worried; everything worked out fine.", espanol: 'No tenía que haberme preocupado; todo salió bien.', opciones: ['have', 'had', 'be'], correcta: 0 },
  ],
  // Tema 39: Lenguaje académico y formal
  39: [
    { id: 1, ingles: 'The results ___ that further research is needed.', espanol: 'Los resultados sugieren que se necesita más investigación.', opciones: ['suggest', 'say', 'tell'], correcta: 0 },
    { id: 2, ingles: 'This essay will ___ the main causes of climate change.', espanol: 'Este ensayo examinará las principales causas del cambio climático.', opciones: ['examine', 'eat', 'build'], correcta: 0 },
    { id: 3, ingles: '___ to the data, unemployment has decreased this year.', espanol: 'Según los datos, el desempleo ha disminuido este año.', opciones: ['According', 'Despite', 'Although'], correcta: 0 },
    { id: 4, ingles: 'The study ___ a strong correlation between sleep and productivity.', espanol: 'El estudio revela una fuerte correlación entre el sueño y la productividad.', opciones: ['reveals', 'cooks', 'drives'], correcta: 0 },
    { id: 5, ingles: 'In ___, the evidence supports the original hypothesis.', espanol: 'En conclusión, la evidencia apoya la hipótesis original.', opciones: ['conclusion', 'addition', 'contrast'], correcta: 0 },
  ],
  // Tema 40: Expresiones idiomáticas avanzadas
  40: [
    { id: 1, ingles: 'He really bit off more than he could chew with that project.', espanol: 'Él realmente asumió más de lo que podía con ese proyecto.', opciones: ['He took on too much responsibility.', 'He ate too much at lunch.', 'He bit someone at work.'], correcta: 0 },
    { id: 2, ingles: "Let's not beat around the bush — what do you really mean?", espanol: 'No andemos con rodeos, ¿qué quieres decir realmente?', opciones: ['Be direct and say what you mean.', 'Stop walking near the bushes.', 'Do not hit the plants outside.'], correcta: 0 },
    { id: 3, ingles: 'She has a lot on her plate right now.', espanol: 'Ella tiene muchas cosas de qué preocuparse ahora.', opciones: ['She is very busy with many things.', 'She has a very full dinner plate.', 'She dropped her food on the floor.'], correcta: 0 },
    { id: 4, ingles: 'The new policy is just a drop in the ocean.', espanol: 'La nueva política es solo una gota en el océano.', opciones: ['It is too small to make a real difference.', 'It fell into the water by accident.', 'It is related to ocean pollution.'], correcta: 0 },
    { id: 5, ingles: 'They went back to the drawing board after the plan failed.', espanol: 'Volvieron al punto de partida después de que el plan falló.', opciones: ['They started the planning process over again.', 'They went to an art class together.', 'They repainted the office whiteboard.'], correcta: 0 },
  ],
  // Tema 41: Escritura profesional y correos
  41: [
    { id: 1, ingles: 'Which opening is most appropriate for a formal email?', espanol: '¿Cuál es la apertura más apropiada para un correo formal?', opciones: ['Dear Mr. Smith,', 'Hey Smith!', 'Yo Smith,'], correcta: 0 },
    { id: 2, ingles: 'I am writing ___ to the job advertisement posted on your website.', espanol: 'Le escribo en referencia al anuncio de empleo publicado en su sitio web.', opciones: ['with reference', 'with food', 'with color'], correcta: 0 },
    { id: 3, ingles: 'Please find ___ my updated resume.', espanol: 'Adjunto encontrará mi currículum actualizado.', opciones: ['attached', 'below', 'inside'], correcta: 0 },
    { id: 4, ingles: 'I would ___ the opportunity to discuss this further.', espanol: 'Agradecería la oportunidad de discutir esto más a fondo.', opciones: ['appreciate', 'eat', 'paint'], correcta: 0 },
    { id: 5, ingles: 'Which closing is most appropriate for a formal letter?', espanol: '¿Cuál es el cierre más apropiado para una carta formal?', opciones: ['Yours sincerely,', 'See ya!', 'Bye bye,'], correcta: 0 },
  ],
  // Tema 42: Fluidez y conversación avanzada
  42: [
    { id: 1, ingles: 'Could you elaborate on that point?', espanol: '¿Podrías ampliar ese punto?', opciones: ['Sure, what I meant was that the results were unexpected.', 'Sure, I am very hungry today.', 'Sure, the weather is quite cold.'], correcta: 0 },
    { id: 2, ingles: 'I tend to ___ when I am under pressure.', espanol: 'Tiendo a bloquearme cuando estoy bajo presión.', opciones: ['freeze up', 'warm up', 'slow down'], correcta: 0 },
    { id: 3, ingles: 'That is an interesting perspective. Have you considered the other side?', espanol: 'Esa es una perspectiva interesante. ¿Has considerado el otro lado?', opciones: ['Yes, and I think both views have merit.', 'Yes, and I think both views are cold.', 'Yes, and I think both views are blue.'], correcta: 0 },
    { id: 4, ingles: 'What I find ___ about learning languages is the cultural insight.', espanol: 'Lo que encuentro más gratificante de aprender idiomas es el conocimiento cultural.', opciones: ['most rewarding', 'most delicious', 'most colorful'], correcta: 0 },
    { id: 5, ingles: 'To wrap things up, what is your main takeaway from today?', espanol: 'Para concluir, ¿cuál es tu principal aprendizaje de hoy?', opciones: ['My main takeaway is that consistency is key to fluency.', 'My main takeaway is that the food was good.', 'My main takeaway is that it was very cold today.'], correcta: 0 },
  ],
};

// Preguntas genéricas de respaldo
export const leccionesPorDefecto: PreguntaLeccion[] = [
  { id: 1, ingles: 'Hello! How are you?', espanol: '¡Hola! ¿Cómo estás?', opciones: ["Hello! I'm fine.", 'Goodbye!', 'My name is Diego.'], correcta: 0 },
  { id: 2, ingles: 'What is your name?', espanol: '¿Cuál es tu nombre?', opciones: ['I am from Colombia.', 'My name is Diego.', "I don't know."], correcta: 1 },
  { id: 3, ingles: 'Nice to meet you!', espanol: '¡Mucho gusto!', opciones: ['See you later!', 'Nice to meet you too!', 'I am tired.'], correcta: 1 },
  { id: 4, ingles: 'Where are you from?', espanol: '¿De dónde eres?', opciones: ['I am from Colombia.', 'I am 30 years old.', 'I like coffee.'], correcta: 0 },
  { id: 5, ingles: 'How old are you?', espanol: '¿Cuántos años tienes?', opciones: ['I am fine.', 'I am 25 years old.', 'I like music.'], correcta: 1 },
];

export function obtenerLeccionesDeTema(temaId: number): PreguntaLeccion[] {
  return leccionesPorTema[temaId] || leccionesPorDefecto;
}
